telemetry = false

[install]
exact = true

[test]
root = "./tests"
preload = ["./tests/setup.ts"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = ["tests/**", "examples/**", "scripts/**", "**/*.data.ts", "**/erfa.ts", "**/types.ts", "**/sgp4.ts", "**/meeus.ts", "**/phd2.ts", "src/devices/**"]
