import { describe, expect, test } from 'bun:test'
import { arcmin, deg, toArcmin, toDeg } from '../src/angle'
import { coordinateToTile, distanceToTile, tileIntersectsDisc, ASTROMETRY_INDEX_MANIFEST, type AstrometryNetIndexRequest, selectAstrometryIndexes } from '../src/astrometrynet.index'
import { PI, TAU } from '../src/constants'
import { coordToPixel } from '../src/healpix'

// Astrometry.net XY fixtures.
//
// Provenance: expected tile ids were produced by a clean-room TypeScript port of Astrometry.net's
// `util/healpix.c` (3-clause BSD; tile numbering `xyztohp`, `healpix_compose_xy`, and the inverse
// `hp_to_xyz`) as published at github.com/dstndstn/astrometry.net. Tile distances use an
// independent conservative edge minimization rather than a port. The fixtures could not be
// regenerated by executing the native binary in this environment, so they are additionally pinned
// by structural invariants verified below: the Nside=1 base-pixel anchors match the documented
// layout, every coordinate maps to a valid id, all 48 tiles at resolution 2 are reachable, and the
// self-distance of a coordinate to its own tile is exactly zero. All angles in the fixtures are in
// degrees only for readability; the API consumes and returns radians.
const TILE_FIXTURES: readonly { readonly ra: number; readonly dec: number; readonly tile: number; readonly label: string }[] = [
	{ ra: 0, dec: 0, tile: 19, label: 'equator RA=0' },
	{ ra: 45, dec: 0, tile: 0, label: 'equator RA=45' },
	{ ra: 180, dec: 0, tile: 27, label: 'equator antimeridian' },
	{ ra: 270, dec: -10, tile: 28, label: 'equatorial mid-latitude' },
	{ ra: 33.3, dec: 12.7, tile: 0, label: 'northern mid-latitude' },
	{ ra: 200, dec: -40, tile: 41, label: 'southern mid-latitude' },
	{ ra: 120, dec: 85, tile: 7, label: 'near north pole' },
	{ ra: 300, dec: -85, tile: 44, label: 'near south pole' },
	{ ra: 0, dec: 89.999, tile: 3, label: 'north polar cap' },
	{ ra: 0, dec: -89.999, tile: 32, label: 'south polar cap' },
	{ ra: 359.5, dec: 1, tile: 19, label: 'RA just below TAU' },
	{ ra: 0.5, dec: -1, tile: 16, label: 'RA just above zero' },
]

// A coordinate where Astrometry.net XY, standard RING, and standard NESTED ids all differ.
const TRIPLE_DIFFER = { ra: 0, dec: -65, xy: 33, ring: 36, nested: 34 }

describe('astrometry.net healpix xy', () => {
	test('Nside=1 base pixels match the documented layout', () => {
		// Equatorial base pixels 4..7 are centered on the equator; north 0..3, south 8..11.
		expect(coordinateToTile(deg(0), deg(0), 1)).toBe(4)
		expect(coordinateToTile(deg(90), deg(0), 1)).toBe(5)
		expect(coordinateToTile(deg(180), deg(0), 1)).toBe(6)
		expect(coordinateToTile(deg(270), deg(0), 1)).toBe(7)
		expect(coordinateToTile(deg(0), deg(89.9), 1)).toBeLessThanOrEqual(3)
		expect(coordinateToTile(deg(0), deg(-89.9), 1)).toBeGreaterThanOrEqual(8)
	})

	test('coordinateToTile matches XY fixtures at resolution 2', () => {
		for (const fixture of TILE_FIXTURES) {
			expect(coordinateToTile(deg(fixture.ra), deg(fixture.dec), 2)).toBe(fixture.tile)
		}
	})

	test('all 48 tiles are reachable and ids are valid', () => {
		const seen = new Set<number>()
		for (let dec = -89; dec <= 89; dec += 0.5) {
			for (let ra = 0; ra < 360; ra += 0.5) {
				const tile = coordinateToTile(deg(ra), deg(dec), 2)
				expect(Number.isInteger(tile)).toBe(true)
				expect(tile).toBeGreaterThanOrEqual(0)
				expect(tile).toBeLessThan(48)
				seen.add(tile)
			}
		}
		expect(seen.size).toBe(48)
	})

	test('a coordinate is at zero distance from its own tile', () => {
		for (let dec = -80; dec <= 80; dec += 7) {
			for (let ra = 3; ra < 360; ra += 13) {
				const tile = coordinateToTile(deg(ra), deg(dec), 2)
				expect(distanceToTile(tile, 2, deg(ra), deg(dec))).toBeLessThan(1e-9)
			}
		}
	})

	test('RA normalization makes wrapped right ascensions equivalent', () => {
		const ra = deg(40)
		const dec = deg(20)
		const base = coordinateToTile(ra, dec, 2)
		expect(coordinateToTile(ra + TAU, dec, 2)).toBe(base)
		expect(coordinateToTile(ra - TAU, dec, 2)).toBe(base)
		expect(coordinateToTile(ra + 5 * TAU, dec, 2)).toBe(base)
		expect(coordinateToTile(ra - 100 * TAU, dec, 2)).toBe(base)
	})

	test('XY tile id differs from RING and NESTED at a known coordinate', () => {
		const ra = deg(TRIPLE_DIFFER.ra)
		const dec = deg(TRIPLE_DIFFER.dec)
		const xy = coordinateToTile(ra, dec, 2)
		const ring = coordToPixel(2, ra, dec, 'ring')
		const nested = coordToPixel(2, ra, dec, 'nested')
		expect(xy).toBe(TRIPLE_DIFFER.xy)
		expect(ring).toBe(TRIPLE_DIFFER.ring)
		expect(nested).toBe(TRIPLE_DIFFER.nested)
		// A RING or NESTED substitution would return a different filename suffix here.
		expect(xy).not.toBe(ring)
		expect(xy).not.toBe(nested)
		expect(ring).not.toBe(nested)
	})

	test('distance is symmetric to the tile boundary and inclusive at contact', () => {
		// A point outside a tile has a positive, finite distance to it.
		const distance = distanceToTile(0, 2, deg(0), deg(0))
		expect(distance).toBeGreaterThan(0)
		expect(distance).toBeLessThan(PI)
		// Boundary is inclusive: a disc whose radius equals the distance intersects the tile.
		expect(tileIntersectsDisc(0, 2, deg(0), deg(0), distance)).toBe(true)
		// A disc slightly smaller does not.
		expect(tileIntersectsDisc(0, 2, deg(0), deg(0), distance - 1e-6)).toBe(false)
	})

	test('distance is the conservative minimum over all tile edges, not an endpoint bisection', () => {
		// Regression: for a center just outside tile 33, the closest boundary point lies on an edge
		// whose far endpoint is not one of the two nearest corners. Astrometry.net's endpoint
		// bisection discarded that edge and reported ~1.477 degrees, but the true minimum distance is
		// ~1.299 degrees. Over-reporting the distance would drop tile 33 from a search disc that
		// actually intersects it, so the edge minimization must return the smaller value.
		const ra = deg(30.818)
		const dec = deg(-55.742)
		const distance = toDeg(distanceToTile(33, 2, ra, dec))
		expect(distance).toBeCloseTo(1.2990764, 4)
		expect(distance).toBeLessThan(1.477)
		// A disc whose radius sits between the true minimum and the old bisection value must intersect.
		expect(tileIntersectsDisc(33, 2, ra, dec, deg(1.4))).toBe(true)
		expect(tileIntersectsDisc(33, 2, ra, dec, deg(1.29))).toBe(false)
	})

	test('invalid resolution and tile ids throw RangeError', () => {
		expect(() => coordinateToTile(deg(0), deg(0), 0)).toThrow(RangeError)
		expect(() => coordinateToTile(deg(0), deg(0), 1.5)).toThrow(RangeError)
		expect(() => distanceToTile(48, 2, deg(0), deg(0))).toThrow(RangeError)
		expect(() => distanceToTile(-1, 2, deg(0), deg(0))).toThrow(RangeError)
	})

	test('non-finite or out-of-range coordinates throw RangeError', () => {
		// Without validation eraS2c would turn these into NaN or a mirrored, plausible-but-wrong tile.
		expect(() => coordinateToTile(Number.NaN, 0, 2)).toThrow(RangeError)
		expect(() => coordinateToTile(0, Number.NaN, 2)).toThrow(RangeError)
		expect(() => coordinateToTile(Number.POSITIVE_INFINITY, 0, 2)).toThrow(RangeError)
		expect(() => coordinateToTile(0, PI / 2 + 1e-6, 2)).toThrow(RangeError)
		expect(() => coordinateToTile(0, -PI / 2 - 1e-6, 2)).toThrow(RangeError)
		expect(() => distanceToTile(0, 2, Number.NaN, 0)).toThrow(RangeError)
		expect(() => distanceToTile(0, 2, 0, PI)).toThrow(RangeError)
		expect(() => tileIntersectsDisc(0, 2, 0, Number.NaN, 0)).toThrow(RangeError)
		// The exact poles remain valid.
		expect(() => coordinateToTile(0, PI / 2, 2)).not.toThrow()
		expect(() => coordinateToTile(0, -PI / 2, 2)).not.toThrow()
	})

	test('non-finite or negative search radius throws RangeError', () => {
		// A NaN radius would otherwise silently return false; a tiny negative radius would otherwise
		// be rescued by INTERSECTION_EPSILON into a false positive for a center inside the tile.
		const inside = coordinateToTile(deg(33), deg(12), 2)
		expect(() => tileIntersectsDisc(inside, 2, deg(33), deg(12), Number.NaN)).toThrow(RangeError)
		expect(() => tileIntersectsDisc(inside, 2, deg(33), deg(12), Number.POSITIVE_INFINITY)).toThrow(RangeError)
		expect(() => tileIntersectsDisc(inside, 2, deg(33), deg(12), -5e-10)).toThrow(RangeError)
		expect(() => tileIntersectsDisc(inside, 2, deg(33), deg(12), -1)).toThrow(RangeError)
		// A zero radius is valid: the center lies inside its own tile, distance 0.
		expect(tileIntersectsDisc(inside, 2, deg(33), deg(12), 0)).toBe(true)
	})
})

// Builds a request, filling required geometry fields with sensible defaults.
function request(overrides: Partial<AstrometryNetIndexRequest> = {}): AstrometryNetIndexRequest {
	return { focalLength: 1000, pixelPitch: 5, width: 1000, height: 1000, ...overrides }
}

describe('camera and field geometry', () => {
	test('sensor dimensions follow the physical pitch', () => {
		const plan = selectAstrometryIndexes(request({ pixelPitch: 3.76, width: 6000, height: 4000 }))
		expect(plan.sensorWidth).toBeCloseTo(6000 * 0.00376, 10)
		expect(plan.sensorHeight).toBeCloseTo(4000 * 0.00376, 10)
	})

	test('central pixel scale uses the exact atan formula', () => {
		const focalLength = 800
		const pixelPitch = 3.8
		const plan = selectAstrometryIndexes(request({ focalLength, pixelPitch }))
		const pitchInMillimetres = pixelPitch / 1000
		expect(plan.pixelScale).toBeCloseTo(2 * Math.atan(pitchInMillimetres / (2 * focalLength)), 14)
	})

	test('horizontal and vertical fields are exact and largest axis is the max', () => {
		const plan = selectAstrometryIndexes(request({ focalLength: 500, pixelPitch: 4, width: 2000, height: 1000 }))
		const sw = 2000 * 0.004
		const sh = 1000 * 0.004
		expect(plan.fieldWidth).toBeCloseTo(2 * Math.atan(sw / (2 * 500)), 14)
		expect(plan.fieldHeight).toBeCloseTo(2 * Math.atan(sh / (2 * 500)), 14)
		expect(plan.largestFieldDimension).toBe(Math.max(plan.fieldWidth, plan.fieldHeight))
		expect(plan.largestFieldDimension).toBe(plan.fieldWidth)
	})

	test('corner radius is computed from the physical diagonal, not the field diagonal', () => {
		const plan = selectAstrometryIndexes(request({ focalLength: 500, pixelPitch: 4, width: 2000, height: 1000 }))
		const halfDiagonal = Math.hypot(2000 * 0.004 * 0.5, 1000 * 0.004 * 0.5)
		expect(plan.fieldCornerRadius).toBeCloseTo(Math.atan(halfDiagonal / 500), 14)
		// The exact corner radius is larger than the small-angle half-hypot of the two fields.
		const smallAngle = 0.5 * Math.hypot(plan.fieldWidth, plan.fieldHeight)
		expect(plan.fieldCornerRadius).not.toBeCloseTo(smallAngle, 14)
	})

	test('small fields approach the small-angle approximation', () => {
		// A long focal length yields a tiny field where 2*atan(s/2f) ~= s/f.
		const focalLength = 4000
		const pixelPitch = 3
		const width = 1000
		const plan = selectAstrometryIndexes(request({ focalLength, pixelPitch, width, height: width }))
		const sensorWidth = width * (pixelPitch / 1000)
		expect(plan.fieldWidth).toBeCloseTo(sensorWidth / focalLength, 6)
	})

	test('wide fields diverge from the small-angle approximation', () => {
		// A short focal length yields a wide field where the exact atan matters.
		const plan = selectAstrometryIndexes(request({ focalLength: 50, pixelPitch: 10, width: 4000, height: 4000 }))
		const sensorWidth = 4000 * 0.01
		const exact = 2 * Math.atan(sensorWidth / (2 * 50))
		const approximation = sensorWidth / 50
		expect(plan.fieldWidth).toBeCloseTo(exact, 14)
		expect(Math.abs(plan.fieldWidth - approximation)).toBeGreaterThan(deg(1))
	})
})

describe('scale selection and coverage', () => {
	// Returns the selected index numbers for a request.
	function selectedIndexNumbers(req: AstrometryNetIndexRequest) {
		return selectAstrometryIndexes(req).scales.map((scale) => scale.indexNumber)
	}

	test('a narrow field selects only 5200 scales', () => {
		// ~10 arcminute field: largest axis well under the 22' 5200/4100 boundary.
		const plan = selectAstrometryIndexes(request({ focalLength: 2000, pixelPitch: 3, width: 2000, height: 2000 }))
		expect(toArcmin(plan.largestFieldDimension)).toBeLessThan(22)
		expect(plan.scales.length).toBeGreaterThan(0)
		for (const scale of plan.scales) expect(scale.family).toBe('5200')
	})

	test('a field exactly on a scale boundary selects both adjacent scales', () => {
		// Force the requested interval to collapse onto the 5203/5204 boundary (8 arcmin) exactly.
		const base = selectAstrometryIndexes(request())
		const fraction = arcmin(8) / base.largestFieldDimension
		const plan = selectAstrometryIndexes(request({ minQuadFraction: fraction, maxQuadFraction: fraction }))
		expect(plan.minimumRequiredQuadDiameter).toBeCloseTo(arcmin(8), 15)
		expect(plan.scales.map((scale) => scale.indexNumber)).toEqual([5203, 5204])
	})

	test('a one-degree-class square field selects 5203..5206 and 4107..4109', () => {
		// A ~0.98 degree square keeps the default 10%..100% window strictly inside 5.9'..58.8',
		// matching Astrometry.net's documented 1-degree recommendation without boundary ties.
		const plan = selectAstrometryIndexes(request({ focalLength: 1000, pixelPitch: 5, width: 3417, height: 3417 }))
		expect(toDeg(plan.largestFieldDimension)).toBeGreaterThan(0.95)
		expect(toDeg(plan.largestFieldDimension)).toBeLessThan(1)
		expect(plan.scales.map((scale) => scale.indexNumber)).toEqual([5203, 5204, 5205, 5206, 4107, 4108, 4109])
	})

	test('a wide field selects only 4100 scales', () => {
		const plan = selectAstrometryIndexes(request({ focalLength: 20, pixelPitch: 10, width: 4000, height: 4000 }))
		expect(plan.scales.length).toBeGreaterThan(0)
		for (const scale of plan.scales) expect(scale.family).toBe('4100')
	})

	test('custom fractions change the requested interval', () => {
		const plan = selectAstrometryIndexes(request({ minQuadFraction: 0.5, maxQuadFraction: 0.75 }))
		expect(plan.minimumRequiredQuadDiameter).toBeCloseTo(plan.largestFieldDimension * 0.5, 15)
		expect(plan.maximumRequiredQuadDiameter).toBeCloseTo(plan.largestFieldDimension * 0.75, 15)
	})

	test('a fully supported interval reports complete coverage', () => {
		// ~1 degree field: 6'..60' lies inside the 2'..2000' manifest range.
		const plan = selectAstrometryIndexes(request({ focalLength: 1000, pixelPitch: 5, width: 3417, height: 3417 }))
		expect(plan.coverage.status).toBe('complete')
		expect(plan.coverage.supportedMinimum).toBeCloseTo(arcmin(2), 15)
		expect(plan.coverage.supportedMaximum).toBeCloseTo(arcmin(2000), 15)
	})

	test('a partially supported interval reports partial coverage', () => {
		// A tiny field pushes the lower endpoint below the 2 arcminute manifest floor.
		const plan = selectAstrometryIndexes(request({ focalLength: 3000, pixelPitch: 3, width: 2000, height: 2000 }))
		expect(toArcmin(plan.minimumRequiredQuadDiameter)).toBeLessThan(2)
		expect(plan.scales.length).toBeGreaterThan(0)
		expect(plan.coverage.status).toBe('partial')
	})

	test('an out-of-range field returns no scales and none coverage without throwing', () => {
		// An extremely long focal length makes even the largest quad smaller than 2 arcminutes.
		const plan = selectAstrometryIndexes(request({ focalLength: 100000, pixelPitch: 1, width: 1000, height: 1000 }))
		expect(plan.scales).toHaveLength(0)
		expect(plan.files).toHaveLength(0)
		expect(plan.coverage.status).toBe('none')
	})

	test('selected scales are returned in ascending scale order', () => {
		// Index numbers are not monotonic across families (5206 precedes 4107), but the scale is.
		const scales = selectAstrometryIndexes(request({ focalLength: 1000, pixelPitch: 5, width: 3417, height: 3417 })).scales
		for (let i = 1; i < scales.length; i++) expect(scales[i].scale).toBeGreaterThan(scales[i - 1].scale)
		expect(selectedIndexNumbers(request({ focalLength: 1000, pixelPitch: 5, width: 3417, height: 3417 }))).toEqual([5203, 5204, 5205, 5206, 4107, 4108, 4109])
	})

	test('invalid geometry, fractions, and dimensions throw RangeError', () => {
		expect(() => selectAstrometryIndexes(request({ focalLength: 0 }))).toThrow(RangeError)
		expect(() => selectAstrometryIndexes(request({ focalLength: Number.NaN }))).toThrow(RangeError)
		expect(() => selectAstrometryIndexes(request({ pixelPitch: -1 }))).toThrow(RangeError)
		expect(() => selectAstrometryIndexes(request({ width: 0 }))).toThrow(RangeError)
		expect(() => selectAstrometryIndexes(request({ width: 1.5 }))).toThrow(RangeError)
		expect(() => selectAstrometryIndexes(request({ height: -10 }))).toThrow(RangeError)
		expect(() => selectAstrometryIndexes(request({ minQuadFraction: 0 }))).toThrow(RangeError)
		expect(() => selectAstrometryIndexes(request({ maxQuadFraction: Number.POSITIVE_INFINITY }))).toThrow(RangeError)
		expect(() => selectAstrometryIndexes(request({ minQuadFraction: 0.5, maxQuadFraction: 0.4 }))).toThrow(RangeError)
		expect(() => selectAstrometryIndexes(request({ center: { rightAscension: deg(10), declination: deg(95) } }))).toThrow(RangeError)
		expect(() => selectAstrometryIndexes(request({ center: { rightAscension: Number.NaN, declination: 0 } }))).toThrow(RangeError)
		expect(() => selectAstrometryIndexes(request({ pointingUncertainty: -0.1, center: { rightAscension: 0, declination: 0 } }))).toThrow(RangeError)
		expect(() => selectAstrometryIndexes(request({ safetyMargin: Number.NaN, center: { rightAscension: 0, declination: 0 } }))).toThrow(RangeError)
	})

	test('finite inputs that overflow derived geometry throw RangeError', () => {
		// pixelPitch * width overflows to Infinity even though both inputs are finite and pass the
		// per-field checks. The atan-based fields would stay finite, so the overflow must be caught
		// at the sensor dimensions rather than leaking Infinity into public geometry.
		expect(() => selectAstrometryIndexes(request({ pixelPitch: 1e300, width: Number.MAX_SAFE_INTEGER }))).toThrow(RangeError)
		expect(() => selectAstrometryIndexes(request({ pixelPitch: 1e300, height: Number.MAX_SAFE_INTEGER }))).toThrow(RangeError)
	})
})

describe('tile selection', () => {
	// A camera giving a ~1 degree field that selects both 5200 and 4100 scales.
	const wideish = request({ focalLength: 1000, pixelPitch: 5, width: 3417, height: 3417 })

	test('without a center every selected 5200 scale expands to all 48 tiles', () => {
		const plan = selectAstrometryIndexes(wideish)
		const tiled = plan.files.filter((file) => file.family === '5200')
		const scales5200 = plan.scales.filter((scale) => scale.family === '5200')
		expect(tiled).toHaveLength(scales5200.length * 48)
		for (const file of tiled) expect(file.reason).toBe('no-field-center')
		// Each tiled scale covers ids 0..47 exactly once.
		const firstScale = scales5200[0].indexNumber
		const ids = plan.files.filter((file) => file.indexNumber === firstScale).map((file) => file.tileId)
		expect(ids).toEqual(Array.from({ length: 48 }, (_, i) => i))
	})

	test('a center near a tile boundary keeps a tile its search disc actually intersects', () => {
		// Regression: a small field centered just outside tile 33, with a search disc (~1.405 degrees)
		// between the tile's true distance (~1.299 degrees) and the old endpoint-bisection value
		// (~1.477 degrees). The tiled scales must include index-520x-33.fits.
		const plan = selectAstrometryIndexes(request({ focalLength: 1000, pixelPitch: 2, width: 436, height: 436, center: { rightAscension: deg(30.818), declination: deg(-55.742) }, safetyMargin: deg(1.37) }))
		expect(toDeg(plan.tileSearchRadius!)).toBeGreaterThan(1.299)
		expect(toDeg(plan.tileSearchRadius!)).toBeLessThan(1.477)
		const tiled = plan.scales.filter((scale) => scale.family === '5200')
		expect(tiled.length).toBeGreaterThan(0)
		for (const scale of tiled) {
			expect(plan.files.some((file) => file.indexNumber === scale.indexNumber && file.tileId === 33)).toBe(true)
		}
	})

	test('a center away from boundaries selects a strict subset of tiles', () => {
		const plan = selectAstrometryIndexes(request({ ...wideish, center: { rightAscension: deg(45), declination: deg(10) } }))
		const scales5200 = plan.scales.filter((scale) => scale.family === '5200')
		const tiled = plan.files.filter((file) => file.family === '5200')
		expect(tiled.length).toBeGreaterThan(0)
		expect(tiled.length).toBeLessThan(scales5200.length * 48)
		for (const file of tiled) expect(file.reason).toBe('tile-intersects-search-disc')
		// The tile containing the center is always included.
		const centerTile = coordinateToTile(deg(45), deg(10), 2)
		const firstScale = scales5200[0].indexNumber
		const ids = plan.files.filter((file) => file.indexNumber === firstScale).map((file) => file.tileId)
		expect(ids).toContain(centerTile)
	})

	test('equivalent right ascensions produce identical selections after normalization', () => {
		const variants = [deg(45), deg(45) + TAU, deg(45) - TAU, deg(45) - 100 * TAU]
		const reference = selectAstrometryIndexes(request({ ...wideish, center: { rightAscension: variants[0], declination: deg(10) } }))
		const referenceNames = reference.files.map((file) => file.filename)
		for (let i = 1; i < variants.length; i++) {
			const plan = selectAstrometryIndexes(request({ ...wideish, center: { rightAscension: variants[i], declination: deg(10) } }))
			expect(plan.files.map((file) => file.filename)).toEqual(referenceNames)
		}
	})

	test('centers near both poles select tiles without error', () => {
		for (const dec of [deg(89.9), deg(-89.9)]) {
			const plan = selectAstrometryIndexes(request({ ...wideish, center: { rightAscension: deg(123), declination: dec } }))
			const tiled = plan.files.filter((file) => file.family === '5200')
			expect(tiled.length).toBeGreaterThan(0)
			const centerTile = coordinateToTile(deg(123), dec, 2)
			const firstScale = plan.scales.find((scale) => scale.family === '5200')!.indexNumber
			expect(plan.files.filter((file) => file.indexNumber === firstScale).map((file) => file.tileId)).toContain(centerTile)
		}
	})

	test('a larger search disc selects more tiles than a smaller one', () => {
		const small = selectAstrometryIndexes(request({ ...wideish, center: { rightAscension: deg(45), declination: deg(0) }, safetyMargin: deg(0.1) }))
		const large = selectAstrometryIndexes(request({ ...wideish, center: { rightAscension: deg(45), declination: deg(0) }, safetyMargin: deg(40) }))
		const smallTiled = small.files.filter((file) => file.family === '5200').length
		const largeTiled = large.files.filter((file) => file.family === '5200').length
		expect(largeTiled).toBeGreaterThan(smallTiled)
	})

	test('a search radius of PI or greater selects all 48 tiles', () => {
		const plan = selectAstrometryIndexes(request({ ...wideish, center: { rightAscension: deg(45), declination: deg(0) }, safetyMargin: deg(200) }))
		const scales5200 = plan.scales.filter((scale) => scale.family === '5200')
		const tiled = plan.files.filter((file) => file.family === '5200')
		expect(plan.tileSearchRadius).toBe(PI)
		expect(tiled).toHaveLength(scales5200.length * 48)
		for (const file of tiled) expect(file.reason).toBe('tile-intersects-search-disc')
	})

	test('no duplicate filenames and a stable sort order', () => {
		const plan = selectAstrometryIndexes(request({ ...wideish, center: { rightAscension: deg(45), declination: deg(10) } }))
		const names = plan.files.map((file) => file.filename)
		expect(new Set(names).size).toBe(names.length)
		// Files are ordered by ascending scale, then ascending tile id.
		for (let i = 1; i < plan.files.length; i++) {
			const previous = plan.files[i - 1]
			const current = plan.files[i]
			if (current.scale === previous.scale) {
				expect(current.tileId ?? -1).toBeGreaterThan(previous.tileId ?? -1)
			} else {
				expect(current.scale).toBeGreaterThan(previous.scale)
			}
		}
	})

	test('changing the center never changes the selected 4100 all-sky filenames', () => {
		const withoutCenter = selectAstrometryIndexes(wideish)
		const withCenter = selectAstrometryIndexes(request({ ...wideish, center: { rightAscension: deg(45), declination: deg(10) } }))
		const allSkyOf = (plan: ReturnType<typeof selectAstrometryIndexes>) => plan.files.filter((file) => file.family === '4100').map((file) => file.filename)
		expect(allSkyOf(withCenter)).toEqual(allSkyOf(withoutCenter))
		for (const file of withCenter.files.filter((f) => f.family === '4100')) {
			expect(file.reason).toBe('all-sky-index')
			expect(file.tileId).toBeUndefined()
		}
	})
})

describe('filenames and integration', () => {
	test('exact tiled filenames index-5200-00.fits and index-5206-47.fits', () => {
		// A ~18 arcminute field with no center selects all tiled scales 0..6, each as 48 files.
		const plan = selectAstrometryIndexes(request({ focalLength: 2000, pixelPitch: 5, width: 2094, height: 2094 }))
		const names = new Set(plan.files.map((file) => file.filename))
		expect(plan.scales.map((scale) => scale.indexNumber)).toEqual([5200, 5201, 5202, 5203, 5204, 5205, 5206])
		expect(names.has('index-5200-00.fits')).toBe(true)
		expect(names.has('index-5206-47.fits')).toBe(true)
	})

	test('exact all-sky filenames index-4107.fits and index-4119.fits', () => {
		// A ~1 degree field yields the smallest all-sky scale 4107.
		const oneDegree = selectAstrometryIndexes(request({ focalLength: 1000, pixelPitch: 5, width: 3417, height: 3417 }))
		expect(new Set(oneDegree.files.map((file) => file.filename)).has('index-4107.fits')).toBe(true)
		// A very wide field reaches the largest all-sky scale 4119.
		const wide = selectAstrometryIndexes(request({ focalLength: 20, pixelPitch: 10, width: 4000, height: 4000 }))
		expect(new Set(wide.files.map((file) => file.filename)).has('index-4119.fits')).toBe(true)
	})

	test('every 5200 descriptor has a tile id and every 4100 descriptor omits it', () => {
		const plan = selectAstrometryIndexes(request({ focalLength: 1000, pixelPitch: 5, width: 3417, height: 3417 }))
		for (const file of plan.files) {
			if (file.family === '5200') {
				expect(file.tileId).toBeGreaterThanOrEqual(0)
				expect(file.tileId).toBeLessThanOrEqual(47)
			} else {
				expect(file.tileId).toBeUndefined()
			}
		}
	})

	test('plan diagnostics are radians using Angle', () => {
		const plan = selectAstrometryIndexes(request({ focalLength: 1000, pixelPitch: 5, width: 3417, height: 3417, center: { rightAscension: deg(45), declination: deg(10) } }))
		// All angular diagnostics are small radian quantities, not degrees or arcminutes.
		expect(plan.pixelScale).toBeLessThan(0.001)
		expect(plan.fieldWidth).toBeLessThan(0.1)
		expect(plan.tileSearchRadius).toBeGreaterThan(0)
		expect(plan.tileSearchRadius).toBeLessThan(PI)
		expect(plan.minimumRequiredQuadDiameter).toBeCloseTo(plan.largestFieldDimension * 0.1, 15)
	})

	test('repeated calls return equivalent ordered descriptors', () => {
		const req = request({ focalLength: 1000, pixelPitch: 5, width: 3417, height: 3417, center: { rightAscension: deg(45), declination: deg(10) } })
		const a = selectAstrometryIndexes(req)
		const b = selectAstrometryIndexes(req)
		expect(a.files.map((file) => file.filename)).toEqual(b.files.map((file) => file.filename))
		expect(a.scales.map((scale) => scale.indexNumber)).toEqual(b.scales.map((scale) => scale.indexNumber))
		expect(a.files.map((file) => file.reason)).toEqual(b.files.map((file) => file.reason))
	})

	test('the manifest is contiguous and covers scales 0 through 19', () => {
		expect(ASTROMETRY_INDEX_MANIFEST).toHaveLength(20)
		for (let i = 1; i < ASTROMETRY_INDEX_MANIFEST.length; i++) {
			expect(ASTROMETRY_INDEX_MANIFEST[i].minimumQuadDiameter).toBeCloseTo(ASTROMETRY_INDEX_MANIFEST[i - 1].maximumQuadDiameter, 15)
		}
		for (const scale of ASTROMETRY_INDEX_MANIFEST) {
			if (scale.family === '5200') expect(scale.tileResolution).toBe(2)
			else expect(scale.tileResolution).toBeUndefined()
		}
	})
})
