import { expect, test } from 'bun:test'
import { isNumberArray, quickSelect } from '../../../src/math/numerical/array'

test('is number array', () => {
	expect(isNumberArray([1, 2, 3])).toBeTrue()
	// expect(isNumberArray([1, '2'])).toBeFalse()
	expect(isNumberArray(new Float64Array([1, 2, 3]))).toBeTrue()
	expect(isNumberArray(new Int32Array([1, 2, 3]))).toBeTrue()
	expect(isNumberArray(new Uint32Array([1, 2, 3]))).toBeTrue()
	expect(isNumberArray(new Int16Array([1, 2, 3]))).toBeTrue()
	expect(isNumberArray(new Uint16Array([1, 2, 3]))).toBeTrue()
	expect(isNumberArray(new Int8Array([1, 2, 3]))).toBeTrue()
	expect(isNumberArray(new Uint8Array([1, 2, 3]))).toBeTrue()
	expect(isNumberArray(new Uint8ClampedArray([1, 2, 3]))).toBeTrue()
	expect(isNumberArray(new Float32Array([1, 2, 3]))).toBeTrue()
	expect(isNumberArray(new Float16Array([1, 2, 3]))).toBeTrue()
	expect(isNumberArray(new BigInt64Array([1n, 2n, 3n]))).toBeFalse()
	expect(isNumberArray(new DataView(new ArrayBuffer(8)))).toBeFalse()
	expect(isNumberArray([])).toBeTrue()
	expect(isNumberArray(['1'])).toBeFalse()
	expect(isNumberArray(new ArrayBuffer(8))).toBeFalse()
	expect(isNumberArray('[1, 2, 3]')).toBeFalse()
	expect(isNumberArray({})).toBeFalse()
	expect(isNumberArray(null)).toBeFalse()
	expect(isNumberArray(undefined)).toBeFalse()
	expect(isNumberArray(123)).toBeFalse()
	expect(isNumberArray(true)).toBeFalse()
})

test('quick select', () => {
	const values = new Float64Array([7, 2, 5, 2, 9, 1, Number.NaN, 100])
	expect(quickSelect(values, 7, 3)).toBe(5)
	expect(values[7]).toBe(100)
	for (let index = 0; index < 3; index++) expect(values[index]).toBeLessThanOrEqual(5)
	for (let index = 4; index < 7; index++) expect(Number.isNaN(values[index]) || values[index] >= 5).toBeTrue()
	expect(quickSelect(values, 7, 6)).toBeNaN()
	expect(() => quickSelect(values, 0, 0)).toThrow(RangeError)
	expect(() => quickSelect(values, 7, 7)).toThrow(RangeError)
})
